@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTgxZDkwOTliYjBmNzdiNDExMDk1YzYiLCJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzcwMTE3Mzg1LCJleHAiOjE4MDE2NTMzODV9.f6U15ljGxWWSMavEzWnu13lyb9g9Qbf5rgvSTRD1vlY
# @url =  http://localhost:4567
@url =  http://192.168.1.82:4567


//updateCostumerProfile
###
PUT {{url}}/api/v1/user/updateCostumerProfile HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
  "firstName": "Julkarnen",
  "lastName": "Qureshi",
  "image": "9876543210"
}


